---
- name: "Instala o Apache em distro derivados do RedHat"
  yum:
    name:
      - httpd
      - openssl
    state: latest
  when: (ansible_facts['os_family'] == "RedHat")
  notify: #handlers
    - enableHttpd

- name: "CriaDirVhostRedHat"
  file:
    path: "/etc/httpd/vhost.d"
    state: directory
  when: (ansible_facts['os_family'] == "RedHat")

- name: "Criar virtual host com as configurações do site - RedHat"
  template:
    src: templates/site.conf
    dest: /etc/httpd/vhost.d/{{ log_prefix }}.conf
  when: (ansible_facts['os_family'] == "RedHat")
  notify:
    - addInHostsFile
    - addInHttpdFile
    - RestartHttpd
    - InstallWordPress
    - SetPermissionWP-CentOS