---
# handlers file for serverTools
- name: addInHostsFile
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  with_items: 
    - "127.0.0.1 {{ hostname }}"
    - "{{inventory_hostname}} {{ hostname }}" #inventory_hostname é o ip que esta no inventario

- name: Restart Server
  reboot:

- name: enable yum-utils
  shell:             # comando que daria no terminal á no host
    cmd: "yum-config-manager -enable remi-php74"
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'